/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 28 nov. 2009, 19:06:12
 */

package simcar;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author YvesFabienne
 */
public class MainFrame extends javax.swing.JFrame  {

    Simcar simcar;
    Timer screenTimer = new Timer();
    //boolean[] keys = new boolean[0xfff];

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();

        simcar = new Simcar();

        simcar.InitApplication();
        simcar.InitInstance();

        long delay = 0;
        long period = 1000/60;
        screenTimer.scheduleAtFixedRate( new TimerTask() {
            public void run() {
                if ( SimCarDisplayer.getInstance() != null) {
                    synchronized(this) {
                        simcar.drawProc();
                    }
                }
                repaint();
            }
        }
                , delay, period);

    }

    public void keyPressed(KeyEvent evt) {
        simcar.keyb[evt.getKeyCode()] = true;
        simcar.keybtr[evt.getKeyCode()] = true;
    }

    public void keyReleased(KeyEvent evt) {
        simcar.keyb[evt.getKeyCode()] = false;
    }

    private void vitessesAuto(ActionEvent evt) {
        String command = evt.getActionCommand();
        simcar.vitauto = vitessesAutomatiques.isSelected();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphicPanel = new simcar.GraphicPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        configurationMenu = new javax.swing.JMenu();
        vitessesAutomatiques = new javax.swing.JCheckBoxMenuItem();
        aideMenu = new javax.swing.JMenu();
        aProposMenuItem = new javax.swing.JMenuItem();
        aideMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SimCar, un simulateur de conduite");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout graphicPanelLayout = new javax.swing.GroupLayout(graphicPanel);
        graphicPanel.setLayout(graphicPanelLayout);
        graphicPanelLayout.setHorizontalGroup(
            graphicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        graphicPanelLayout.setVerticalGroup(
            graphicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(graphicPanel, java.awt.BorderLayout.CENTER);

        configurationMenu.setText("Configuration");

        vitessesAutomatiques.setSelected(true);
        vitessesAutomatiques.setText("Vitesses automatiques");
        vitessesAutomatiques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitessesAutomatiquesActionPerformed(evt);
            }
        });
        configurationMenu.add(vitessesAutomatiques);

        jMenuBar1.add(configurationMenu);

        aideMenu.setText("Aide");

        aProposMenuItem.setText("A propos...");
        aProposMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aProposMenuItemActionPerformed(evt);
            }
        });
        aideMenu.add(aProposMenuItem);

        aideMenuItem.setText("Aide...");
        aideMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aideMenuItemActionPerformed(evt);
            }
        });
        aideMenu.add(aideMenuItem);

        jMenuBar1.add(aideMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
      keyPressed(evt);
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        keyReleased(evt);
    }//GEN-LAST:event_formKeyReleased

    private void vitessesAutomatiquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitessesAutomatiquesActionPerformed
        vitessesAuto(evt);
    }//GEN-LAST:event_vitessesAutomatiquesActionPerformed

    private void aProposMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aProposMenuItemActionPerformed
        aPropos();
    }//GEN-LAST:event_aProposMenuItemActionPerformed

    private void aideMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aideMenuItemActionPerformed
        aide();
    }//GEN-LAST:event_aideMenuItemActionPerformed

    void aPropos() {
        JOptionPane.showMessageDialog(this, "SimCar version 3.0, Yves Boyadjian 2015");
    }

    void aide() {
        StringBuilder message = new StringBuilder();
        message.append("Vous êtes au volant d'une Peugeot 305 SR.\n");
        message.append("Le but du jeu est de parcourir une distance fixe en un minimum de temps.\n");
        message.append("Pour changer de vitesses en mode manuel, utilisez les touches 'w' et 'x'\n");
        JOptionPane.showMessageDialog(this, message);
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    public void setVisible(boolean visible) {
        if (!visible) {
            screenTimer.cancel();
            simcar.dispose();
        }
        super.setVisible(visible);
    }
/*
    @Override
    public synchronized void paint(Graphics g) {
        //super.paint(g);


        SimCarDisplayer.checkDimensions(getWidth(),getHeight(),this);

        SimCarDisplayer.draw(g, rootPane);
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aProposMenuItem;
    private javax.swing.JMenu aideMenu;
    private javax.swing.JMenuItem aideMenuItem;
    private javax.swing.JMenu configurationMenu;
    private simcar.GraphicPanel graphicPanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JCheckBoxMenuItem vitessesAutomatiques;
    // End of variables declaration//GEN-END:variables


}
